service: nestjs-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    NODE_ENV: production

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  patterns:
    - '!node_modules/**'
    - 'dist/**'
    - 'package.json'